config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create] do
    member do
      get :activate
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessor :password, :password_confirmation

  validates :first_name, :last_name, :email, :password_confirmation, presence: true
  validates :password, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_to :root, notice: 'Successfully signed in'
    else
      flash[:alert] = "Couldn't sign in"
      render :new
    end
  end

  def destroy
    logout
    redirect_to :root, notice: 'Signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :root, notice: 'Successfully signed up'
    else
      render :new
    end
  end

  def activate
    if @user = User.load_from_activation_token(params[:id])
      @user.activate!
      redirect_to signin_path, :notice => 'User was successfully activated.'
    else
      not_authenticated
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TenPercentNews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav role='main navigation'>
    <%= link_to 'Home', root_path %>
    <%- if logged_in? %>
      <%= link_to 'Sign Out', signout_path, method: :delete %>
      <p>Hello, <%= current_user.first_name %></p>
    <% else %>
      <%= link_to 'Sign Up', signup_path %>
      <%= link_to 'Sign In', signin_path %>
    <% end %>
  </nav>


  <div id="flashes">
    <%- flash.each do |class_name, message| %>
      <div class="<%= class_name %>"><%= message %></div>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= simple_form_for @user do |form| %>
  <%= form.input :first_name %>
  <%= form.input :last_name %>
  <%= form.input :email %>
  <%= form.input :password %>
  <%= form.input :password_confirmation %>
  <%= form.button :submit, 'Sign Up' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>